# Generated by Django 4.1.3 on 2024-03-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemonAPI', '0006_order_remove_menuitem_inventory_menuitem_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='featured',
            field=models.BooleanField(db_index=True, default='False'),
        ),
    ]
